login:
    pattern: /login
    defaults: { _controller: AtekiaFlowlyBundle:Security:login }

login_check:
    pattern: /login_check
    #schemes:  [https]

logout:
    pattern: /logout

atekia_flowly:
    resource: "@AtekiaFlowlyBundle/Resources/config/routing.yml"
    prefix:   /
