atekia_flowly_home:
    path:  /
    defaults: { _controller: AtekiaFlowlyBundle:Home:index }

atekia_flowly_hello:
    path:  /hello/{name}
    defaults: { _controller: AtekiaFlowlyBundle:Default:index }

atekia_flowly_admin_manageusers:
    path:  /admin/manageusers
    defaults: { _controller: AtekiaFlowlyBundle:Security:manageusers }

atekia_flowly_admin_manageusers_disabled:
    path:  /admin/manageusers/disabled
    defaults: { _controller: AtekiaFlowlyBundle:Security:manageusers, active: false }

atekia_flowly_admin_manageusers_enableuser:
    path:  /admin/manageusers/enable/{user}
    defaults: { _controller: AtekiaFlowlyBundle:Security:enable, active: true }
    requirements:
        user:  \d+

atekia_flowly_admin_manageusers_disableuser:
    path:  /admin/manageusers/disable/{user}
    defaults: { _controller: AtekiaFlowlyBundle:Security:enable, active: false }
    requirements:
        user:  \d+

atekia_flowly_admin_edituser:
    path:  /admin/manageusers/user/{user}
    defaults: { _controller: AtekiaFlowlyBundle:Security:edituser }
    requirements:
        user:  \d+

#atekia_flowly_admin_adduser:
#    path:  /admin/manageusers/adduser
#    methods:   [GET]
#    defaults:
#        _controller: FrameworkBundle:Template:template
#        template:    'AtekiaFlowlyBundle:Security:adduser.html.twig'

atekia_flowly_admin_adduser:
    path:  /admin/manageusers/adduser
    defaults: { _controller: AtekiaFlowlyBundle:Security:adduser }