# HOME #

atekia_flowly_home:
    path:  /
    defaults: { _controller: AtekiaFlowlyBundle:Home:index }

# ERROR #

atekia_flowly_error:
    path:  /error
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'TwigBundle:Exception:error.html.twig'

# USERS #

atekia_flowly_admin_manageusers:
    path:  /admin/users
    defaults: { _controller: AtekiaFlowlyBundle:Security:manageusers }

atekia_flowly_admin_manageusers_disabled:
    path:  /admin/users/disabled
    defaults: { _controller: AtekiaFlowlyBundle:Security:manageusers, active: false }

atekia_flowly_admin_manageusers_enableuser:
    path:  /admin/users/enable/{user}
    defaults: { _controller: AtekiaFlowlyBundle:Security:enable, active: true }
    requirements:
        user:  \d+

atekia_flowly_admin_manageusers_disableuser:
    path:  /admin/users/disable/{user}
    defaults: { _controller: AtekiaFlowlyBundle:Security:enable, active: false }
    requirements:
        user:  \d+

atekia_flowly_admin_edituser:
    path:  /admin/users/user/{userid}
    defaults: { _controller: AtekiaFlowlyBundle:Security:edituser }
    requirements:
        userid:  \d+

atekia_flowly_admin_adduser:
    path:  /admin/users/add
    defaults: { _controller: AtekiaFlowlyBundle:Security:adduser }

atekia_flowly_user_config:
    path:  /user/config
    defaults: { _controller: AtekiaFlowlyBundle:Security:edituser }

# PROVIDERS #

atekia_flowly_expenses_manageproviders:
    path:  /expenses/providers
    defaults: { _controller: AtekiaFlowlyBundle:Expenses:manageproviders }

atekia_flowly_expenses_manageproviders_removeprovider:
    path:  /expenses/providers/remove/{id}
    defaults: { _controller: AtekiaFlowlyBundle:Expenses:removeprovider }
    requirements:
        id:  \d+

atekia_flowly_expenses_editprovider:
    path:  /expenses/providers/provider/{id}
    defaults: { _controller: AtekiaFlowlyBundle:Expenses:editprovider }
    requirements:
        id:  \d+

atekia_flowly_expenses_addprovider:
    path:  /expenses/providers/add
    defaults: { _controller: AtekiaFlowlyBundle:Expenses:addprovider }

# CLIENTS #

atekia_flowly_revenues_manageclients:
    path:  /revenues/clients
    defaults: { _controller: AtekiaFlowlyBundle:Revenues:manageclients }

atekia_flowly_revenues_manageclients_removeclient:
    path:  /revenues/clients/remove/{id}
    defaults: { _controller: AtekiaFlowlyBundle:Revenues:removeclient }
    requirements:
        id:  \d+

atekia_flowly_revenues_editclient:
    path:  /revenues/clients/client/{id}
    defaults: { _controller: AtekiaFlowlyBundle:Revenues:editclient }
    requirements:
        id:  \d+

atekia_flowly_revenues_addclient:
    path:  /revenues/clients/add
    defaults: { _controller: AtekiaFlowlyBundle:Revenues:addclient }