atekia_flowly_home:
    pattern:  /
    defaults: { _controller: AtekiaFlowlyBundle:Home:index }

atekia_flowly_hello:
    pattern:  /hello/{name}
    defaults: { _controller: AtekiaFlowlyBundle:Default:index }

atekia_flowly_admin_manageusers:
    pattern:  /admin/manageusers
    defaults: { _controller: AtekiaFlowlyBundle:Security:manageusers }

atekia_flowly_admin_manageusers_disabled:
    pattern:  /admin/manageusers/disabled
    defaults: { _controller: AtekiaFlowlyBundle:Security:manageusers, active: false }

atekia_flowly_admin_manageusers_enableuser:
    pattern:  /admin/manageusers/enable/{user}
    defaults: { _controller: AtekiaFlowlyBundle:Security:enable, active: true }
    requirements:
        user:  \d+

atekia_flowly_admin_manageusers_disableuser:
    pattern:  /admin/manageusers/disable/{user}
    defaults: { _controller: AtekiaFlowlyBundle:Security:enable, active: false }
    requirements:
        user:  \d+

atekia_flowly_admin_edituser:
    pattern:  /admin/manageusers/user/{user}
    defaults: { _controller: AtekiaFlowlyBundle:Security:edituser }
    requirements:
        user:  \d+

atekia_flowly_admin_adduser:
    pattern:  /admin/manageusers/adduser
    defaults: { _controller: AtekiaFlowlyBundle:Security:adduser }